# Define the required gems for this theme.
# http://bundler.io/v1.3/gemfile.html

# Grab gems from the RubyGems server.
source 'https://rubygems.org'

# Use ~> to to allow newer minor versions within the same major version.
# Remove ~> to require a specific version.
gem 'sass', '~>3.4.12'
gem 'compass', '~>1.0.3'
gem 'sass-globbing', '1.1.0'
gem 'sassy-maps', '~>0.4.0'
gem 'breakpoint', '~>2.5.0'
gem 'singularitygs', '~>1.4'
gem 'quotation-marks'